id: Vendr.Cart
name: Cart
type: Package
description: 
supportedBy: core

packageVersion: 1.0.0
docVersions:
  next: 
  current: 1.0.0
  pervious: 

links:
  - title: Versions
    link: /versions/
  - title: Changelog
    link: /changelog/