id: Vendr.PaymentProviders.PayPal
name: PayPal
type: PaymentProvider
description: 
supportedBy: core

packageVersion: 1.0.0
docVersions:
  next: 1.0.1
  current: 1.0.0
  previous: 
    - 0.1.0

links:
  - title: Versions
    link: /versions/
  - title: Changelog
    link: /changelog/