id: Vendr
name: Vendr
type: Product
description: 
supportedBy: core

packageVersion: 1.0.0
docVersions:
  current: 1.0.0
  previous: 

links:
  - title: Versions
    link: /versions/
  - title: Changelog
    link: /changelog/