id: Vendr
name: Vendr
type: Product
description: 
supportedBy: core
links:
  - title: Versions
    link: /versions/
  - title: Changelog
    link: /changelog/
versions:
  next: 1.0.1
  current: 1.0.0
  previous: 
    - 0.1.0