id: Vendr
name: Vendr
type: Product
description: 
supportedBy: core

packageVersion: 1.2.1
docVersions:
  next: 1.3.0
  current: 1.0.0
  previous: 
    - 0.8.0
    - 0.1.0

links:
  - title: Versions
    link: /versions/
  - title: Changelog
    link: /changelog/