id: Vendr.PaymentProviders.Dibs
name: DIBS
logo: dibs.png
type: PaymentProvider
supportedBy: core

packageVersion: 1.0.0
docVersions:
  next: 
  current: 1.0.0
  previous: 

links:
  - title: Versions
    link: /versions/
  - title: Changelog
    link: /changelog/