id: Vendr.Contrib.PaymentProviders.Buckaroo
name: Buckaroo
logo: buckaroo.svg
type: PaymentProvider
supportedBy: community

packageVersion: 0.2.0
docVersions:
  next: 
  current: 0.1.0
  previous: 

links:
  - title: Versions
    link: /versions/
  - title: Changelog
    link: /changelog/