id: Vendr.Contrib.PaymentProviders.QuickPay
name: QuickPay
logo: quickpay.svg
type: PaymentProvider
supportedBy: community

packageVersion: 1.1.0
docVersions:
  next: 
  current: 1.0.0
  previous: 

links:
  - title: Versions
    link: /versions/
  - title: Changelog
    link: /changelog/
