id: Vendr.PaymentProviders.Stripe
name: Stripe
logo: stripe.svg
type: PaymentProvider
supportedBy: core

packageVersion: 1.1.0
docVersions:
  next: 
  current: 1.1.0
  previous: 
    - 1.0.0

links:
  - title: Versions
    link: /versions/
  - title: Changelog
    link: /changelog/