id: Vendr.PaymentProviders.PayPal
name: PayPal
logo: paypal.svg
type: PaymentProvider
supportedBy: core

packageVersion: 2.0.1
docVersions:
  next: 
  current: 2.0.0
  previous: 

links:
  - title: Versions
    link: /versions/
  - title: Changelog
    link: /changelog/