id: Vendr.PaymentProviders.Stripe
name: Stripe
type: PaymentProvider
description: 
supportedBy: core
links:
  - title: Versions
    link: /versions/
  - title: Changelog
    link: /changelog/
versions:
  current: 1.0.0
  previous: 
    - 0.1.0