extends: substitution
message: Prefer %s over '%s.'
level: warning
ignorecase: false
swap:
  back office: back-office
  backoffice: back-office
  app_plugins: App_Plugins
  vue: Vue
  powershell: PowerShell
  Powershell: PowerShell
  javascript: JavaScript
  Javascript: JavaScript
  html: HTML
  Html: HTML