id: Vendr
name: Vendr
type: Product
description: 
supportedBy: core

packageVersion: 1.3.0
docVersions:
  next: 
  current: 1.3.0
  previous: 
  - 1.2.0
  - 1.0.0

links:
  - title: Versions
    link: /versions/
  - title: Changelog
    link: /changelog/