id: Vendr.Checkout
name: Checkout
type: Package
description: 
supportedBy: core

packageVersion: 1.1.6
docVersions:
  next: 
  current: 1.1.0
  previous: 
    - 1.0.0

links:
  - title: Versions
    link: /versions/
  - title: Changelog
    link: /changelog/