id: Vendr.Reviews
name: Reviews
type: Package
description: 
supportedBy: community

packageVersion: 0.1.0
docVersions:
  next: 
  current: 0.1.0
  pervious: 

links:
  - title: Versions
    link: /versions/
  - title: Changelog
    link: /changelog/